# Gemini FastAPI Configuration File

server:
  host: "0.0.0.0"          # Server bind address
  port: 8000               # Server port
  api_key: null            # API key for authentication (null for no auth)

cors:
  enabled: true            # Enable CORS
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

gemini:
  clients:
    - id: "primary-client"   # Arbitrary client ID
      secure_1psid: "YOUR_SECURE_1PSID_HERE"
      secure_1psidts: "YOUR_SECURE_1PSIDTS_HERE"
  timeout: 60              # Init timeout in seconds
  auto_refresh: true       # Auto-refresh session cookies
  refresh_interval: 540    # Refresh interval in seconds
  verbose: false           # Enable verbose logging for Gemini requests
  max_chars_per_request: 1000000     # Maximum characters Gemini Web accepts per request. Non-pro users might have a lower limit

storage:
  path: "./data/lmdb"        # Database storage path
  max_size: 134217728      # Maximum database size (128 MB)

logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL