version: '3.8'

services:
  gemini-api:
    image: devinglaw/genmini2api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
      - ./cache:/app/.venv/lib/python3.12/site-packages/gemini_webapi/utils/temp
      - ./config.yaml:/app/config.yaml:ro  # 添加配置文件映射
    env_file:
      - .env
    environment:
      - SECURE_1PSID=${SECURE_1PSID}
      - SECURE_1PSIDTS=${SECURE_1PSIDTS}
      - API_KEY=${API_KEY}
      - GEMINI_PROXY=${GEMINI_PROXY}
      - LOG_LEVEL=info
      - TZ=Asia/Shanghai
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s  # 增加启动时间
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
    command: ""
