services:
  - type: web
    name: gemi2api-server
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    repo: https://github.com/swhesong/Gemi2Api-Server
    branch: main
    envVars:
      - key: SECURE_1PSID
        sync: false
      - key: SECURE_1PSIDTS
        sync: false
      - key: API_KEY
        sync: false
      - key: GEMINI_PROXY
        sync: false
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
    healthCheckPath: /health
    autoDeploy: true
    startCommand: python start.py
